use super::settings::Language;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TextKey {
    Appearance,
    Applying,
    Battery,
    BatteryError,
    Charging,
    ChooseLanguage,
    Connected,
    Critical,
    Dark,
    DeviceUnavailable,
    Discharging,
    DpiControlsUnavailable,
    DpiFailed,
    DpiNotVerified,
    EnglishLabel,
    Exit,
    Full,
    Good,
    InvalidPreset,
    LanguageLabel,
    Light,
    Low,
    MultipleDevices,
    MultipleDevicesDetected,
    OpenLogiPeek,
    PointerSpeed,
    Presets,
    Refresh,
    Save,
    SettingsSaveFailed,
    SettingsSaved,
    SimplifiedChineseLabel,
    StatusUnavailable,
    System,
    Unknown,
    Unavailable,
    Verified,
    Welcome,
    WorkerBusy,
}

pub fn text(language: Language, key: TextKey) -> &'static str {
    use Language::{English, SimplifiedChinese};
    use TextKey::*;
    match (language, key) {
        (English, Appearance) => "Appearance",
        (English, Applying) => "Applying",
        (English, Battery) => "Battery",
        (English, BatteryError) => "Battery error",
        (English, Charging) => "Charging",
        (English, ChooseLanguage) => "Choose your language",
        (English, Connected) => "Connected",
        (English, Critical) => "Critical",
        (English, Dark) => "Dark",
        (English, DeviceUnavailable) => "Device unavailable",
        (English, Discharging) => "Discharging",
        (English, DpiControlsUnavailable) => "DPI controls unavailable",
        (English, DpiFailed) => "DPI change failed; refresh the device and try again",
        (English, DpiNotVerified) => "DPI change could not be verified",
        (English, EnglishLabel) => "English",
        (English, Exit) => "Exit",
        (English, Full) => "Full",
        (English, Good) => "Good",
        (English, InvalidPreset) => "Presets must be 1-65535",
        (English, LanguageLabel) => "Language",
        (English, Light) => "Light",
        (English, Low) => "Low",
        (English, MultipleDevices) => "Multiple devices",
        (English, MultipleDevicesDetected) => "Multiple Logitech devices detected",
        (English, OpenLogiPeek) => "Open LogiPeek",
        (English, PointerSpeed) => "POINTER SPEED",
        (English, Presets) => "Presets",
        (English, Refresh) => "Refresh",
        (English, Save) => "Save",
        (English, SettingsSaveFailed) => "Settings could not be saved",
        (English, SettingsSaved) => "Settings saved",
        (English, SimplifiedChineseLabel) => "简体中文",
        (English, StatusUnavailable) => "Status unavailable",
        (English, System) => "System",
        (English, Unknown) => "Unknown",
        (English, Unavailable) => "Unavailable",
        (English, Verified) => "Verified",
        (English, Welcome) => "Welcome to LogiPeek",
        (English, WorkerBusy) => "HID worker is busy; try again",
        (SimplifiedChinese, Appearance) => "外观",
        (SimplifiedChinese, Applying) => "正在应用",
        (SimplifiedChinese, Battery) => "电量",
        (SimplifiedChinese, BatteryError) => "电池错误",
        (SimplifiedChinese, Charging) => "正在充电",
        (SimplifiedChinese, ChooseLanguage) => "选择语言",
        (SimplifiedChinese, Connected) => "已连接",
        (SimplifiedChinese, Critical) => "严重不足",
        (SimplifiedChinese, Dark) => "深色",
        (SimplifiedChinese, DeviceUnavailable) => "设备不可用",
        (SimplifiedChinese, Discharging) => "未充电",
        (SimplifiedChinese, DpiControlsUnavailable) => "DPI 控件不可用",
        (SimplifiedChinese, DpiFailed) => "DPI 更改失败；请刷新设备后重试",
        (SimplifiedChinese, DpiNotVerified) => "无法验证 DPI 更改",
        (SimplifiedChinese, EnglishLabel) => "English",
        (SimplifiedChinese, Exit) => "退出",
        (SimplifiedChinese, Full) => "已充满",
        (SimplifiedChinese, Good) => "良好",
        (SimplifiedChinese, InvalidPreset) => "预设值必须为 1-65535",
        (SimplifiedChinese, LanguageLabel) => "语言",
        (SimplifiedChinese, Light) => "浅色",
        (SimplifiedChinese, Low) => "电量低",
        (SimplifiedChinese, MultipleDevices) => "多个设备",
        (SimplifiedChinese, MultipleDevicesDetected) => "检测到多个 Logitech 设备",
        (SimplifiedChinese, OpenLogiPeek) => "打开 LogiPeek",
        (SimplifiedChinese, PointerSpeed) => "指针速度",
        (SimplifiedChinese, Presets) => "预设",
        (SimplifiedChinese, Refresh) => "刷新",
        (SimplifiedChinese, Save) => "保存",
        (SimplifiedChinese, SettingsSaveFailed) => "无法保存设置",
        (SimplifiedChinese, SettingsSaved) => "设置已保存",
        (SimplifiedChinese, SimplifiedChineseLabel) => "简体中文",
        (SimplifiedChinese, StatusUnavailable) => "状态不可用",
        (SimplifiedChinese, System) => "跟随系统",
        (SimplifiedChinese, Unknown) => "未知",
        (SimplifiedChinese, Unavailable) => "不可用",
        (SimplifiedChinese, Verified) => "已验证",
        (SimplifiedChinese, Welcome) => "欢迎使用 LogiPeek",
        (SimplifiedChinese, WorkerBusy) => "HID 工作线程正忙，请重试",
    }
}
